#!/bin/bash
# Manual smoke test for npx cerber init
# Run this in a clean temporary directory

set -e

echo "🧪 Cerber Init - Manual Smoke Test"
echo "=================================="
echo ""

# Create test directory
TEST_DIR="/tmp/cerber-smoke-test-$(date +%s)"
mkdir -p "$TEST_DIR"
cd "$TEST_DIR"

echo "📁 Test directory: $TEST_DIR"
echo ""

# Test 1: Init without CERBER.md (should create template)
echo "Test 1: Init without CERBER.md"
echo "-------------------------------"
npm init -y > /dev/null 2>&1
npx cerber-core init --dry-run

if [ ! -f "CERBER.md" ]; then
  echo "❌ FAILED: CERBER.md should be created"
  exit 1
fi

echo "✅ PASSED: CERBER.md template created"
echo ""

# Test 2: Init with CERBER.md (should generate files)
echo "Test 2: Init with CERBER.md (dry-run)"
echo "--------------------------------------"
npx cerber-core init --dry-run

echo "✅ PASSED: Dry-run completed without errors"
echo ""

# Test 3: Init with actual file generation
echo "Test 3: Init with file generation"
echo "----------------------------------"
npx cerber-core init

# Check expected files
EXPECTED_FILES=(
  "scripts/cerber-guardian.mjs"
  ".husky/pre-commit"
  "src/cerber/health-checks.ts"
  "src/cerber/health-route.ts"
  ".github/workflows/cerber.yml"
)

for file in "${EXPECTED_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "❌ FAILED: Expected file not created: $file"
    exit 1
  fi
  echo "✅ Found: $file"
done

echo ""
echo "✅ PASSED: All expected files created"
echo ""

# Test 4: Check generated file comments
echo "Test 4: Check generated file markers"
echo "------------------------------------"
if ! grep -q "Generated by Cerber init" scripts/cerber-guardian.mjs; then
  echo "❌ FAILED: Guardian script missing 'Generated by Cerber init' comment"
  exit 1
fi

if ! grep -q "Generated by Cerber init" .github/workflows/cerber.yml; then
  echo "❌ FAILED: Workflow missing 'Generated by Cerber init' comment"
  exit 1
fi

echo "✅ PASSED: Generated markers found"
echo ""

# Test 5: Init with --force (should overwrite)
echo "Test 5: Init with --force flag"
echo "-------------------------------"
echo "# MODIFIED" >> scripts/cerber-guardian.mjs
npx cerber-core init --force

if grep -q "# MODIFIED" scripts/cerber-guardian.mjs; then
  echo "❌ FAILED: --force did not overwrite file"
  exit 1
fi

echo "✅ PASSED: --force overwrites files"
echo ""

# Test 6: Check package.json script
echo "Test 6: Check package.json scripts"
echo "-----------------------------------"
if ! grep -q "cerber:guardian" package.json; then
  echo "❌ FAILED: package.json missing cerber:guardian script"
  exit 1
fi

echo "✅ PASSED: package.json updated"
echo ""

# Test 7: Different modes
echo "Test 7: Init with different modes"
echo "----------------------------------"
rm -rf scripts .husky src .github
npx cerber-core init --mode solo --dry-run
echo "✅ PASSED: Solo mode"

rm -rf scripts .husky src .github
npx cerber-core init --mode team --dry-run
echo "✅ PASSED: Team mode"
echo ""

# Test 8: Flag combinations
echo "Test 8: Init with flag combinations"
echo "------------------------------------"
rm -rf scripts .husky src .github
npx cerber-core init --no-husky --no-workflow --no-health --dry-run
echo "✅ PASSED: Multiple no-* flags"
echo ""

# Cleanup
echo "🧹 Cleaning up test directory..."
cd /
rm -rf "$TEST_DIR"

echo ""
echo "=================================="
echo "🎉 ALL SMOKE TESTS PASSED!"
echo "=================================="
