# Funding & Sponsorship

# GitHub Sponsors
github: Agaslez

# Buy Me A Coffee (update after account creation)
# custom: ['https://www.buymeacoffee.com/stefanpitek']

# Other platforms (add when available)
# patreon: cerbercore
# open_collective: cerber-core
# ko_fi: stefanpitek
