# Funding & Sponsorship

# GitHub Sponsors
github: Agaslez

# Buy Me A Coffee
custom: ['https://www.buymeacoffee.com/agataslezak']

# Other platforms (add when available)
# patreon: cerbercore
# open_collective: cerber-core
# ko_fi: agataslezak
