/**
 * Cerber Generator: Creates CERBER.md and CI workflows from contract.yml
 * Command: npm run cerber:generate
 * 
 * This command generates:
 * 1. CERBER.md - Human-readable documentation
 * 2. .github/workflows/cerber-pr-fast.yml - PR workflow (fast checks only)
 * 3. .github/workflows/cerber-main-heavy.yml - Main/nightly workflow (heavy checks)
 * 4. .github/CODEOWNERS - If team mode
 * 
 * All generated files include auto-generated header
 */

import { mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { parse } from 'yaml';
import { logger } from '../core/logger.js';

export interface ContractYaml {
  contractVersion: number;
  name: string;
  version: string;
  metadata: Record<string, any>;
  gates: Record<string, any>;
  testTags: Record<string, any>;
  protectedFiles: Record<string, any>;
  profiles: Record<string, any>;
  generation: Record<string, any>;
}

const AUTO_GENERATED_HEADER = '<!-- AUTO-GENERATED BY CERBER — DO NOT EDIT -->';
const AUTO_GENERATED_HEADER_YML = '# AUTO-GENERATED BY CERBER — DO NOT EDIT';

/**
 * Load and parse contract.yml
 */
export function loadContract(contractPath: string): ContractYaml {
  try {
    const content = readFileSync(contractPath, 'utf-8');
    const contract = parse(content) as ContractYaml;
    logger.info(`✅ Loaded contract from ${contractPath}`);
    return contract;
  } catch (error) {
    logger.error(`Failed to load contract: ${(error as Error).message}`);
    throw error;
  }
}

/**
 * Generate CERBER.md documentation
 */
export function generateCerberMd(contract: ContractYaml, cwd: string): string {
  const md: string[] = [];

  md.push(AUTO_GENERATED_HEADER);
  md.push('');
  md.push('# Cerber Gates & Test Organization');
  md.push('');
  md.push(`Generated from: \`.cerber/contract.yml\` (${contract.version})`);
  md.push('');

  // Gates section
  md.push('## CI Gates');
  md.push('');
  md.push('### Fast Gate (PR Required)');
  md.push('');
  if (contract.gates?.fast) {
    const fast = contract.gates.fast;
    md.push(`**Description:** ${fast.description}`);
    md.push(`**Timeout:** ${fast.timeout}s`);
    md.push('');
    md.push('**Commands:**');
    (fast.commands || []).forEach((cmd: string) => {
      md.push(`- \`${cmd}\``);
    });
    md.push('');
    md.push('**Test Filters:**');
    (fast.testFilters || []).forEach((filter: string) => {
      md.push(`- \`${filter}\``);
    });
    md.push('');
    md.push('**Excluded Tests:**');
    (fast.excludeTests || []).forEach((test: string) => {
      md.push(`- \`${test}\``);
    });
  }

  md.push('');
  md.push('### Heavy Gate (Main/Nightly)');
  md.push('');
  if (contract.gates?.heavy) {
    const heavy = contract.gates.heavy;
    md.push(`**Description:** ${heavy.description}`);
    md.push(`**Timeout:** ${heavy.timeout}s`);
    md.push('');
    md.push('**Jobs:**');
    (heavy.jobs || []).forEach((job: any) => {
      md.push(`- \`${job.name}\`: ${job.description}`);
    });
    md.push('');
    md.push('**Test Tags:**');
    (heavy.testTags || []).forEach((tag: string) => {
      md.push(`- \`${tag}\``);
    });
  }

  // Test Tags section
  md.push('');
  md.push('## Test Tags Organization');
  md.push('');
  Object.entries(contract.testTags || {}).forEach(([tag, config]: [string, any]) => {
    md.push(`### @${tag}`);
    md.push(`**${config.name}**`);
    md.push(`${config.description}`);
    md.push('');
    md.push(`- Command: \`${config.command}\``);
    md.push(`- Timeout: ${config.timeout}ms`);
    md.push(`- Max Retries: ${config.maxRetries}`);
    md.push('');
  });

  // Protected Files section
  md.push('## Protected Files');
  md.push('');
  if (contract.protectedFiles?.autoGeneratedPatterns) {
    md.push('### Auto-Generated (Do Not Edit)');
    contract.protectedFiles.autoGeneratedPatterns.forEach((pattern: any) => {
      md.push(`- \`${pattern.path}\` (source: \`${pattern.source}\`)`);
    });
    md.push('');
  }

  if (contract.protectedFiles?.manualEditPatterns) {
    md.push('### Manual Edits OK');
    contract.protectedFiles.manualEditPatterns.forEach((pattern: any) => {
      md.push(`- \`${pattern.path}\` - ${pattern.description}`);
    });
    md.push('');
  }

  // Commands section
  md.push('## Available Commands');
  md.push('');
  md.push('```bash');
  md.push('npm run test:fast          # Fast unit tests only (@fast)');
  md.push('npm run test:integration   # Integration tests (@integration)');
  md.push('npm run test:e2e           # End-to-end tests (@e2e)');
  md.push('npm run test:signals       # Signal handling tests (@signals)');
  md.push('npm run cerber:generate    # Regenerate this file from contract');
  md.push('npm run cerber:drift       # Check for drift vs contract');
  md.push('```');
  md.push('');

  md.push('## Workflows');
  md.push('');
  md.push('- **`.github/workflows/cerber-pr-fast.yml`**: PR validation (fast checks)');
  md.push('- **`.github/workflows/cerber-main-heavy.yml`**: Main/nightly (all checks)');
  md.push('');
  md.push('---');
  md.push('');
  md.push('To regenerate this file: `npm run cerber:generate`');

  const content = md.join('\n');
  const path = join(cwd, 'CERBER.md');
  writeFileSync(path, content, 'utf-8');
  logger.info(`✅ Generated CERBER.md (${content.length} bytes)`);
  return path;
}

/**
 * Generate cerber-pr-fast.yml workflow
 */
export function generatePrFastWorkflow(contract: ContractYaml, cwd: string): string {
  const lines: string[] = [];

  lines.push(AUTO_GENERATED_HEADER_YML);
  lines.push('');
  lines.push('name: Cerber Fast Checks (PR)');
  lines.push('');
  lines.push('on:');
  lines.push('  pull_request:');
  lines.push('    branches: [main]');
  lines.push('  workflow_dispatch:');
  lines.push('');
  lines.push('env:');
  lines.push('  NODE_VERSION: 20');
  lines.push('');
  lines.push('jobs:');
  lines.push('  lint_and_typecheck:');
  lines.push('    name: Lint & Type Check');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run lint || echo "⚠️  ESLint skipped"');
  lines.push('      - run: npx tsc --noEmit');
  lines.push('');
  lines.push('  build_and_unit:');
  lines.push('    name: Build & Unit Tests (@fast)');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: lint_and_typecheck');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: chmod +x bin/*.cjs bin/cerber* || true');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run build');
  lines.push('      - run: npm run test:fast');
  lines.push('        env:');
  lines.push('          CERBER_TEST_MODE: "1"');
  lines.push('');
  lines.push('  pr_summary:');
  lines.push('    name: PR Summary');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: [lint_and_typecheck, build_and_unit]');
  lines.push('    if: always()');
  lines.push('    steps:');
  lines.push('      - run: |');
  lines.push('          if [[ "${{ needs.lint_and_typecheck.result }}" != "success" ]] || \\');
  lines.push('             [[ "${{ needs.build_and_unit.result }}" != "success" ]]; then');
  lines.push('            echo "❌ Fast gate failed"');
  lines.push('            exit 1');
  lines.push('          fi');
  lines.push('          echo "✅ All fast checks passed"');

  const content = lines.join('\n');
  const dir = join(cwd, '.github', 'workflows');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'cerber-pr-fast.yml');
  writeFileSync(path, content, 'utf-8');
  logger.info(`✅ Generated cerber-pr-fast.yml (${content.length} bytes)`);
  return path;
}

/**
 * Generate cerber-main-heavy.yml workflow
 */
export function generateMainHeavyWorkflow(contract: ContractYaml, cwd: string): string {
  const lines: string[] = [];

  lines.push(AUTO_GENERATED_HEADER_YML);
  lines.push('');
  lines.push('name: Cerber Heavy Verification (Main)');
  lines.push('');
  lines.push('on:');
  lines.push('  push:');
  lines.push('    branches: [main]');
  lines.push('  workflow_dispatch:');
  lines.push('');
  lines.push('env:');
  lines.push('  NODE_VERSION: 20');
  lines.push('  INIT_TIMEOUT_SECONDS: 90');
  lines.push('');
  lines.push('jobs:');
  lines.push('  lint_and_typecheck:');
  lines.push('    name: Lint & Type Check');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run lint || echo "⚠️  ESLint skipped"');
  lines.push('      - run: npx tsc --noEmit');
  lines.push('');
  lines.push('  build_and_unit:');
  lines.push('    name: Build & Unit Tests (@fast)');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: lint_and_typecheck');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: chmod +x bin/*.cjs bin/cerber* || true');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run build');
  lines.push('      - run: npm run test:fast');
  lines.push('        env:');
  lines.push('          CERBER_TEST_MODE: "1"');
  lines.push('');
  lines.push('  integration_tests:');
  lines.push('    name: Integration Tests (@integration)');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: build_and_unit');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run build');
  lines.push('      - run: npm run test:integration');
  lines.push('        env:');
  lines.push('          CERBER_TEST_MODE: "1"');
  lines.push('');
  lines.push('  e2e_tests:');
  lines.push('    name: E2E Tests (@e2e)');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: build_and_unit');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run build');
  lines.push('      - run: npm run test:e2e');
  lines.push('        env:');
  lines.push('          CERBER_TEST_MODE: "1"');
  lines.push('');
  lines.push('  signals_tests:');
  lines.push('    name: Signal Handling Tests (@signals)');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs: build_and_unit');
  lines.push('    steps:');
  lines.push('      - uses: actions/checkout@v4');
  lines.push('      - uses: actions/setup-node@v4');
  lines.push('        with:');
  lines.push('          node-version: ${{ env.NODE_VERSION }}');
  lines.push('      - run: npm ci');
  lines.push('      - run: npm run build');
  lines.push('      - run: npm run test:signals');
  lines.push('        env:');
  lines.push('          CERBER_TEST_MODE: "1"');
  lines.push('');
  lines.push('  summary:');
  lines.push('    name: All Checks Summary');
  lines.push('    runs-on: ubuntu-latest');
  lines.push('    needs:');
  lines.push('      - lint_and_typecheck');
  lines.push('      - build_and_unit');
  lines.push('      - integration_tests');
  lines.push('      - e2e_tests');
  lines.push('      - signals_tests');
  lines.push('    if: always()');
  lines.push('    steps:');
  lines.push('      - run: |');
  lines.push('          if [[ "${{ needs.lint_and_typecheck.result }}" != "success" ]] || \\');
  lines.push('             [[ "${{ needs.build_and_unit.result }}" != "success" ]] || \\');
  lines.push('             [[ "${{ needs.integration_tests.result }}" != "success" ]] || \\');
  lines.push('             [[ "${{ needs.e2e_tests.result }}" != "success" ]] || \\');
  lines.push('             [[ "${{ needs.signals_tests.result }}" != "success" ]]; then');
  lines.push('            echo "❌ One or more checks failed"');
  lines.push('            exit 1');
  lines.push('          fi');
  lines.push('          echo "✅ All checks passed"');

  const content = lines.join('\n');
  const dir = join(cwd, '.github', 'workflows');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'cerber-main-heavy.yml');
  writeFileSync(path, content, 'utf-8');
  logger.info(`✅ Generated cerber-main-heavy.yml (${content.length} bytes)`);
  return path;
}

/**
 * Main generator function - runs all generators
 */
export async function runGenerator(cwd: string = process.cwd()): Promise<void> {
  try {
    const contractPath = join(cwd, '.cerber', 'contract.yml');
    const contract = loadContract(contractPath);

    // Generate all files
    generateCerberMd(contract, cwd);
    generatePrFastWorkflow(contract, cwd);
    generateMainHeavyWorkflow(contract, cwd);

    logger.info('✅ All files generated successfully');
    logger.info('');
    logger.info('Generated files:');
    logger.info('  - CERBER.md');
    logger.info('  - .github/workflows/cerber-pr-fast.yml');
    logger.info('  - .github/workflows/cerber-main-heavy.yml');
    logger.info('');
    logger.info('Run: npm run cerber:drift (to check for drift)');
  } catch (error) {
    logger.error(`Generator failed: ${(error as Error).message}`);
    process.exit(1);
  }
}

// Export for testing
export default { runGenerator, loadContract, generateCerberMd, generatePrFastWorkflow, generateMainHeavyWorkflow };
