/**
 * ⚠️  CERBER TEMPLATE (NOT SOURCE OF TRUTH)
 * 
 * This file is a starting point. Edit it to match YOUR architecture.
 * The source of truth is CERBER.md.
 * 
 * Generated by: npx cerber init
 * Project: {{PROJECT_NAME}}
 * 
 * See: https://github.com/Agaslez/cerber-core#guardian-configuration
 */

export const BACKEND_SCHEMA = {
  version: "1.0.0",
  
  // Your architecture rules (customize)
  rules: [],
  
  // Patterns that should never appear in your code
  forbiddenPatterns: [
    // ──────────────────────────────────────────────────────────────────────
    // 🔐 SECURITY BASELINE (Uncomment and adapt to your CERBER.md contract)
    // ──────────────────────────────────────────────────────────────────────
    
    // Hardcoded secrets (common examples - adapt to your stack):
    // {
    //   pattern: "password\\s*=\\s*['\"][^'\"]+['\"]"  ,
    //   flags: "i",
    //   name: "Hardcoded passwords (e.g., password='admin123')",
    //   severity: "error"
    // },
    // {
    //   pattern: "api[_-]?key\\s*=\\s*['\"][^'\"]+['\"]"  ,
    //   flags: "i",
    //   name: "Hardcoded API keys (e.g., API_KEY='xyz')",
    //   severity: "error"
    // },
    // {
    //   pattern: "JWT_SECRET\\s*=\\s*['\"][^'\"]+['\"]"  ,
    //   flags: "i",
    //   name: "Hardcoded JWT secrets",
    //   severity: "error"
    // },
    
    // Development artifacts (should not reach production):
    // {
    //   pattern: "console\\.log\\(",
    //   flags: "g",
    //   name: "console.log (use proper logging)",
    //   severity: "warning"
    // },
    // {
    //   pattern: "debugger;",
    //   flags: "g",
    //   name: "debugger statement",
    //   severity: "warning"
    // },
    
    // TODOs that should be resolved before commit:
    // {
    //   pattern: "TODO_REMOVE|FIXME_REMOVE",
    //   flags: "i",
    //   name: "Unresolved critical TODOs",
    //   severity: "error"
    // },
    
    // ──────────────────────────────────────────────────────────────────────
    // ⚠️  IMPORTANT: Uncomment patterns that match rules in your CERBER.md
    // Never invent rules. Only translate what's documented in your contract.
    // ──────────────────────────────────────────────────────────────────────
  ]
};

export default BACKEND_SCHEMA;

/**
 * 💡 Next Steps:
 * 
 * 1. Define your project structure in CERBER.md (single source of truth)
 * 2. Add forbiddenPatterns for your tech stack
 * 3. Add requiredImports rules for your architecture layers
 * 4. Test with: npx cerber-guardian
 * 
 * Full examples:
 * - node_modules/cerber-core/examples/backend-schema.ts
 * - node_modules/cerber-core/examples/frontend-schema.ts
 */
