# Generated by Cerber init
# Protected Cerber assets - require owner approval for changes

# Core contract and schema
/CERBER.md {{OWNERS}}
/{{SCHEMA_FILE}} {{OWNERS}}
/BACKEND_SCHEMA.* {{OWNERS}}

# CI/CD enforcement
/.github/workflows/cerber.yml {{OWNERS}}

# Pre-commit guardian
/scripts/cerber-guardian.mjs {{OWNERS}}
/.husky/pre-commit {{OWNERS}}

# Ownership meta-file (self-protection)
/.github/CODEOWNERS {{OWNERS}}
